const
    PIKE_COLOR_PRIMARY = "#772432",
    KSU_COLOR_PRIMARY = "#512888",
    GREEK_LIFE_COLOR_PRIMARY = "green",
    WHITE = "#FFF",
    LITE_WHITE = "#F8F8F8",
    GAINSBORO_GRAY = "#DCDCDC",
    DARK_GRAY = "#404040"

export {
    PIKE_COLOR_PRIMARY, WHITE, DARK_GRAY, LITE_WHITE, KSU_COLOR_PRIMARY, GREEK_LIFE_COLOR_PRIMARY, GAINSBORO_GRAY
}